<% from "tests.inc.yml" import build, calc_cache_key, restore_cache -%>
name: Tests with reflection validation

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - "REFL-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    <%- call build() -%>

    - name: Compute cache keys
      env:
        GIST_TOKEN: ${{ secrets.CI_BOT_GIST_TOKEN }}
      run: |
        << calc_cache_key()|indent >>
    <%- endcall %>

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    <<- restore_cache() >>

    # Run the test

    - name: Test
      env:
        EDGEDB_DEBUG_DELTA_VALIDATE_REFLECTION: 1
      run: |
        edb test -j2 -v
